In [28]:
%run ./Load_Wine_data.ipynb

Red (1599, 12)
White (4898, 12)
Total (6497, 13)

Normalizing Data

In [29]:
norm_col = df_total.columns[:len(df_total.columns)-2]
df_norm = df_total.copy()
norm_col

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [31]:
for cname in norm_col:
    
    #df_norm[cname] = np.log(df_total[cname]) #pq df total tambem recebe o log?
    df_norm[cname] = np.log(df_norm[cname]+1)

In [32]:
df_norm

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,red
0,2.079442,0.239017,0.307485,3.077312,0.044017,3.828641,5.141664,0.693647,1.386294,0.371564,2.282382,6,0
1,1.987874,0.262364,0.292670,0.955511,0.047837,2.708050,4.890349,0.690143,1.458615,0.398776,2.351375,6,0
2,2.208274,0.246860,0.336472,2.066863,0.048790,3.433987,4.584967,0.690694,1.449269,0.364643,2.406945,6,0
3,2.104134,0.207014,0.277632,2.251292,0.056380,3.871201,5.231109,0.690945,1.432701,0.336472,2.388763,6,0
4,2.104134,0.207014,0.277632,2.251292,0.056380,3.871201,5.231109,0.690945,1.432701,0.336472,2.388763,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,1.974081,0.470004,0.076961,1.098612,0.086178,3.496508,3.806662,0.690594,1.492904,0.457425,2.442347,5,1
6493,1.931521,0.438255,0.095310,1.163151,0.060154,3.688879,3.951244,0.690704,1.508512,0.565314,2.501436,6,1
6494,1.987874,0.412110,0.122218,1.193922,0.073250,3.401197,3.713572,0.691015,1.486140,0.559616,2.484907,6,1
6495,1.931521,0.497740,0.113329,1.098612,0.072321,3.496508,3.806662,0.690880,1.519513,0.536493,2.415914,5,1
6496,1.945910,0.270027,0.385262,1.526056,0.064851,2.944439,3.761200,0.690890,1.479329,0.506818,2.484907,6,1

PLOTTING

In [34]:
faixa_dinamica = pd.concat([df_norm.min(),df_norm.max()],axis =1)
faixa_dinamica.columns = ['Min','Max']
faixa_dinamica['Range'] =faixa_dinamica['Max'] - faixa_dinamica['Min']
faixa_dinamica

                           Min       Max     Range
fixed acidity         1.568616  2.827314  1.258698
volatile acidity      0.076961  0.947789  0.870828
citric acid           0.000000  0.978326  0.978326
residual sugar        0.470004  4.201703  3.731699
chlorides             0.008960  0.476855  0.467895
free sulfur dioxide   0.693147  5.669881  4.976734
total sulfur dioxide  1.945910  6.089045  4.143135
density               0.686681  0.712450  0.025768
pH                    1.313724  1.611436  0.297712
sulphates             0.198851  1.098612  0.899761
alcohol               2.197225  2.766319  0.569095
quality               3.000000  9.000000  6.000000
red                   0.000000  1.000000  1.000000

In [35]:
df_norm[(df_norm['citric acid']==0)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,red
115,1.871802,0.395415,0.0,0.916291,0.062975,2.197225,4.644391,0.690143,1.532557,0.336472,2.370244,4,0
300,1.960095,0.343590,0.0,0.955511,0.061095,3.610918,4.477337,0.688838,1.451614,0.512824,2.468100,6,0
302,1.960095,0.343590,0.0,0.955511,0.061095,3.610918,4.477337,0.688838,1.451614,0.512824,2.468100,6,0
780,1.945910,0.332894,0.0,0.875469,0.041142,2.079442,4.025352,0.688813,1.474763,0.322083,2.501436,4,0
862,1.757858,0.292670,0.0,2.014903,0.027615,3.526361,5.099866,0.690093,1.472472,0.476234,2.388763,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6353,2.014903,0.641854,0.0,0.955511,0.050693,2.302585,2.890372,0.690479,1.504077,0.488580,2.476538,6,1
6359,1.974081,0.579418,0.0,1.131402,0.058269,1.945910,2.639057,0.691466,1.523880,0.476234,2.397895,4,1
6448,2.091864,0.518794,0.0,1.193922,0.083422,2.890372,3.295837,0.692062,1.492904,0.425268,2.351375,5,1
6449,2.091864,0.512824,0.0,1.193922,0.079735,2.944439,3.332205,0.691987,1.490654,0.431782,2.341806,5,1
6451,2.116256,0.551007,0.0,1.163151,0.076961,2.944439,3.367296,0.691971,1.483875,0.470004,2.341806,5,1